DROP TABLE IF EXISTS `e_broadcast`;
CREATE TABLE IF NOT EXISTS `e_broadcast` (
  `id` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `aid` INT(11) NOT NULL DEFAULT '0',
  `cid` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(25) NOT NULL DEFAULT '',
  `message` VARCHAR(255) NOT NULL DEFAULT '',
  `time` INT(11) NOT NULL DEFAULT '0',
  `status` TINYINT(3) NOT NULL DEFAULT '1',
  `repeat` TINYINT(3) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=MYISAM;